workflows:
  kivy_workflow:
    name: "Kivy Build"
    # Remove the 'image' field, it's not necessary in the environment section
    environment:
      operating_system: macos  # Select the macOS environment for iOS builds
      flutter: stable  # If you're not using Flutter, you can remove this line
      xcode: latest  # Use the latest version of Xcode
    scripts:
      - name: Install dependencies
        script: |
          sudo apt update
          sudo apt install -y git zip unzip build-essential libssl-dev libffi-dev python3-dev python3-venv python3-pip
          pip install --upgrade pip virtualenv
          pip install buildozer cython
          sudo apt install -y buildozer
      - name: Build the APK (or iOS App)
        script: |
          buildozer ios debug  # Change to `buildozer android debug` for APK builds
    artifacts:
      - build/outputs/*  # Collect the output files such as APK or iOS build
