workflows:
  ios:
    name: iOS build for Kivy app
    max_build_duration: 60 # Max build time in minutes
    environment:
      vars:
        FLUTTER: stable # Optional if you're using Flutter
      macos:
        version: latest # Or specify the exact macOS version you need
        xcode: latest  # Use the latest Xcode version for iOS builds
    scripts:
      - name: Install dependencies
        script: |
          brew install python3
          brew install libffi
          pip install --upgrade pip virtualenv
          pip install buildozer cython
          sudo apt install -y buildozer
      - name: Run Buildozer iOS build
        script: |
          buildozer ios debug  # iOS build command
    artifacts:
      - build/outputs/*  # This will include the IPA or related iOS build artifacts
