workflows:
  ios:
    name: iOS Build for Kivy App
    max_build_duration: 60 # Max build duration in minutes
    environment:
      flutter: stable # If you're building a Flutter project, otherwise remove this line
    scripts:
      - name: Install dependencies
        script: |
          brew install python3
          brew install libffi
          pip install --upgrade pip virtualenv
          pip install buildozer cython
          brew install pkg-config
          brew install sdl2
          brew install automake
      - name: Run Buildozer iOS build
        script: |
          buildozer ios debug  # Command to build iOS version using Buildozer
    artifacts:
      - build/ios/ipa/*.ipa  # Path to the generated IPA files (check your output directories)

